### PR TITLE
xmlGetProp support

### PR DESCRIPTION
**Pull request by anathematic**
Hello! First of all *thanks a ton for this project* - it's been huge in helping me optimise a bunch of XML file reading.

I've run into some issues with lack of `xmlGetProp` support, I'm relatively new to Elixir (and have no C experience) so I've had some issues adding it myself.

If you can give me some pointers for the C I'd be happy to finish this off myself!

Thanks again! 🧡🧡

### CODE REVIEW

**Comment by melpon** [comment]
It is difficult to add this function, so I will implement it. Thank you for using the library and pull request!

**Comment by melpon** [comment]
I released libxml-1.1.3 includes `Libxml.Nif.xml_get_prop/2` and `Libxml.get_prop/2`.

**Comment by anathematic** [comment]
Wow thanks a bunch @melpon! I'll give it a whirl now!

**Comment by melpon** [comment]
@anathematic I could not reply to the mail you sent. The reply mail address was invalid. So I will reply here.
I am not interested in investigating the feature. But I am interested in making libxml better.
If you have a function you want to add to libxml, please write it in the issue.

**Pull request merged**
